__version__: 0.1.6
transform:
  __class_fullname__: volumentations.core.composition.Compose
  additional_targets: {}
  p: 1.0
  transforms:
    - __class_fullname__: volumentations.augmentations.transforms.Scale3d
      always_apply: true
      p: 0.5
      scale_limit:
        - - -0.1
          - 0.1
        - - -0.1
          - 0.1
        - - -0.1
          - 0.1
    - __class_fullname__: volumentations.augmentations.transforms.RotateAroundAxis3d
      always_apply: true
      axis:
        - 0
        - 0
        - 1
      p: 0.25
      rotation_limit:
        - -0.08754424
        - 0.08754424
    - __class_fullname__: volumentations.augmentations.transforms.RotateAroundAxis3d
      always_apply: true
      axis:
        - 0
        - 1
        - 0
      p: 0.25
      rotation_limit:
        - -0.08754424
        - 0.08754424
    - __class_fullname__: volumentations.augmentations.transforms.RotateAroundAxis3d
      always_apply: true
      axis:
        - 1
        - 0
        - 0
      p: 0.25
      rotation_limit:
        - -0.08754424
        - 0.08754424