python3 run_eval.py --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints   --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt crop --clip_num_crop_levels 1 --clip_crop_expansion_ratio 0.1 > ../_dumps/results/clip_visual_prompt_abls/crop_1_10.txt 
python3 run_eval.py  --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints  --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt crop --clip_num_crop_levels 3 --clip_crop_expansion_ratio 0.1 > ../_dumps/results/clip_visual_prompt_abls/crop_3_10.txt
python3 run_eval.py --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints   --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt crop --clip_num_crop_levels 3 --clip_crop_expansion_ratio 0.15 > ../_dumps/results/clip_visual_prompt_abls/crop_3_15.txt
python3 run_eval.py  --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints  --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt crop --clip_num_crop_levels 3 --clip_crop_expansion_ratio 0.2 > ../_dumps/results/clip_visual_prompt_abls/crop_3_20.txt
python3 run_eval.py  --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints  --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt crop-mask --clip_num_crop_levels 1 --clip_crop_expansion_ratio 0.15 > ../_dumps/results/clip_visual_prompt_abls/cropmask_1_15.txt
python3 run_eval.py  --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints  --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt crop-mask --clip_num_crop_levels 3 --clip_crop_expansion_ratio 0.10 > ../_dumps/results/clip_visual_prompt_abls/cropmask_3_10.txt
python3 run_eval.py --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints   --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt crop-mask --clip_num_crop_levels 3 --clip_crop_expansion_ratio 0.15 > ../_dumps/results/clip_visual_prompt_abls/cropmask_3_15.txt
python3 run_eval.py  --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints  --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt crop-mask --clip_num_crop_levels 3 --clip_crop_expansion_ratio 0.20 > ../_dumps/results/clip_visual_prompt_abls/cropmask_3_20.txt
python3 run_eval.py --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints   --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt mask-blur > ../_dumps/results/clip_visual_prompt_abls/maskblur.txt
python3 run_eval.py --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints   --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt mask-gray > ../_dumps/results/clip_visual_prompt_abls/maskgray.txt
python3 run_eval.py --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints   --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt mask-out > ../_dumps/results/clip_visual_prompt_abls/maskout.txt
python3 run_eval.py --split val --chp_folder /home/p300488/REGRAD-Ref/data/Blender-new/checkpoints   --voxel_size 0.004 --sim_thr 0.95 --use_obj_prior 1 --use_similarity 1 --visual_prompt mask-out,mask-gray,mask-blur > ../_dumps/results/clip_visual_prompt_abls/maskblur,gray,out.txt


